name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v5
      with:
        name: codygman-test-cachix-action
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        skipNixBuild: true
    - name: Build custom emacs
      run: nix-build emacs.nix | cachix push codygman-test-cachix-action
    - name: Run emacs user tests
      run: emacs -nw --load load-init-then-run-ert.el
